name: Release Norimsoft.MinimalEndpoints
run-name: 'v${{ github.event.inputs.version }}'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        type: string

jobs:
  push-nuget-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'v${{ github.event.inputs.version }}'

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'
      - name: Build packages
        run: make pack c=Release
      - name: Push packages
        env:
          API_KEY: ${{ secrets.NUGET_API_KEY }}
          NUGET_URL: https://api.nuget.org/v3/index.json
        run: dotnet nuget push ./nugets/*.nupkg --skip-duplicate --source ${{ env.NUGET_URL }} --api-key ${{ env.API_KEY }}
